services:
  db:

    image: pgvector/pgvector:pg16
    container_name: MyAiToolDb_container
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty741!
      POSTGRES_DB: MyAiToolDb
    volumes:

      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2: