
services:
  db:
    image: ankane/pgvector:latest
    container_name: MyAiToolDb_container
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty741!
      POSTGRES_DB: MyAiToolDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data: